-- SQL Schema Script for Dr. Gordian Veterinary Database on Supabase

-- 1. Create Pets Table
CREATE TABLE IF NOT EXISTS public.pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    species TEXT NOT NULL CHECK (species IN ('Perro', 'Gato')),
    breed TEXT NOT NULL,
    gender TEXT NOT NULL CHECK (gender IN ('Macho', 'Hembra')),
    age_years INT DEFAULT 0,
    age_months INT DEFAULT 0,
    weight_kg NUMERIC(5,2) NOT NULL,
    chip_number TEXT,
    avatar_url TEXT,
    owner_name TEXT NOT NULL,
    owner_phone TEXT NOT NULL,
    owner_email TEXT,
    owner_address TEXT,
    notes TEXT,
    registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Clinical Visits Table
CREATE TABLE IF NOT EXISTS public.visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT REFERENCES public.pets(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    reason TEXT NOT NULL,
    diagnosis TEXT,
    treatment TEXT,
    vet_name TEXT DEFAULT 'Dr. Gordian',
    weight_kg NUMERIC(5,2),
    cost NUMERIC(10,2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Vaccines & Deworming Table
CREATE TABLE IF NOT EXISTS public.vaccines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT REFERENCES public.pets(id) ON DELETE CASCADE,
    vaccine_name TEXT NOT NULL,
    applied_date DATE NOT NULL,
    next_due_date DATE NOT NULL,
    batch_number TEXT,
    status TEXT CHECK (status IN ('Al día', 'Próxima', 'Vencida')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Public Policies for quick access
ALTER TABLE public.pets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vaccines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select pets" ON public.pets FOR SELECT USING (true);
CREATE POLICY "Allow public insert pets" ON public.pets FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pets" ON public.pets FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pets" ON public.pets FOR DELETE USING (true);

CREATE POLICY "Allow public select visits" ON public.visits FOR SELECT USING (true);
CREATE POLICY "Allow public insert visits" ON public.visits FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update visits" ON public.visits FOR UPDATE USING (true);
CREATE POLICY "Allow public delete visits" ON public.visits FOR DELETE USING (true);

CREATE POLICY "Allow public select vaccines" ON public.vaccines FOR SELECT USING (true);
CREATE POLICY "Allow public insert vaccines" ON public.vaccines FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update vaccines" ON public.vaccines FOR UPDATE USING (true);
CREATE POLICY "Allow public delete vaccines" ON public.vaccines FOR DELETE USING (true);
